### ISSUE TITLE
Tries to connect to the external IP even though "localhost" provided in plugin.json

### ISSUE THREAD

**Issue by alex-silentale** [thoersch/new-relic-cassandra#1]
Please note that I redacted the actual external ip.
Possibly the 'localhost' is getting overwritten by information from the ring.

``````
INFO: New Relic monitor started
[2015-08-10 20:15:50,295] ERROR com.tylerhoersch.nr.cassandra.JMXRunner - 
java.lang.Exception: All hosts (<external ip of this machine>) tried and failed to connect.
    at com.tylerhoersch.nr.cassandra.JMXRunner.run(Unknown Source) [plugin.jar:1.0.0 July 29 2015]
    at com.tylerhoersch.nr.cassandra.CassandraAgent.getCassandraMetrics(Unknown Source) [plugin.jar:1.0.0 July 29 2015]
    at com.tylerhoersch.nr.cassandra.CassandraAgent.pollCycle(Unknown Source) [plugin.jar:1.0.0 July 29 2015]
    at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:209) [plugin.jar:1.0.0 July 29 2015]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_51]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_51]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_51]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_51]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: <external ip of this machine>; nested exception is: 
    java.net.ConnectException: Connection refused]
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_51]
    at java.util.concurrent.FutureTask.get(FutureTask.java:206) [na:1.8.0_51]
    at com.tylerhoersch.nr.cassandra.JMXRunner.connectWithTimeout(Unknown Source) [plugin.jar:1.0.0 July 29 2015]
    ... 11 common frames omitted
Caused by: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: <external ip of this machine>; nested exception is: 
    java.net.ConnectException: Connection refused]
    at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369) ~[na:1.8.0_51]
    at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[na:1.8.0_51]
    at com.tylerhoersch.nr.cassandra.JMXRunner.lambda$connectWithTimeout$2(Unknown Source) [plugin.jar:1.0.0 July 29 2015]
    at com.tylerhoersch.nr.cassandra.JMXRunner$$Lambda$1/1283157949.call(Unknown Source) ~[na:na]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_51]
    ... 3 common frames omitted
Caused by: javax.naming.ServiceUnavailableException: null
    at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:122) ~[na:1.8.0_51]
    at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205) ~[na:1.8.0_51]
    at javax.naming.InitialContext.lookup(InitialContext.java:417) ~[na:1.8.0_51]
    at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1957) ~[na:1.8.0_51]
    at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1924) ~[na:1.8.0_51]
    at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287) ~[na:1.8.0_51]
    ... 7 common frames omitted
Caused by: java.rmi.ConnectException: Connection refused to host: <external ip of this machine>; nested exception is: 
    java.net.ConnectException: Connection refused
    at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[na:1.8.0_51]
    at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216) ~[na:1.8.0_51]
    at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202) ~[na:1.8.0_51]
    at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:342) ~[na:1.8.0_51]
    at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source) ~[na:1.8.0_51]
    at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:118) ~[na:1.8.0_51]
    ... 12 common frames omitted
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_51]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_51]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_51]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_51]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_51]
    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_51]
    at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_51]
    at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_51]
    at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_51]
    at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40) ~[na:1.8.0_51]
    at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148) ~[na:1.8.0_51]
    at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613) ~[na:1.8.0_51]
    ... 17 common frames omitted
[2015-08-10 20:15:50,305] ERROR com.tylerhoersch.nr.cassandra.CassandraAgent - Error Polling Cassandra: java.lang.Exception: All hosts (<external ip of this machine>) tried and failed to connect.```
``````

**Comment by thoersch** [comment]
The IP specified will be used to talk with the JMX service running to get a full list of IPs in the data center(s).  Based on each of these IPs, the plugin will need to reach out to each node to gather statistics for each as the data exposed via JMX is mostly for the connected node. 

So although your config may only specify 1 address, that address is merely used to discover the rest of the nodes.

**Comment by alex-silentale** [comment]
Thanks for the quick and informative answer.

_Not a Bug_
