### ISSUE TITLE
All hosts tried and failed to connect error

### ISSUE THREAD

**Issue by njain1985** [thoersch/new-relic-cassandra#14]
Hello,

We have a Cassandra cluster setup which we wish to monitor using your plugin. We have currently deployed a single plugin instance that will poll the metrics using JMX. As the plugin is local to the Cassandra cluster, we have disabled remote JMX connection and authentication. Plus, we have already setup JMX password, copied a valid license key and set the logs to debug, set the roles & password in the plugin.json file together with Cassandra instance IPs (comma separated), port (7199) etc.

Upon restarting the Cassandra cluster with your plugin we receive the following errors. We are really keen on leveraging New Relic platform to manage our environment. Please help us asap.  

**The plugin logs are as below:**

root@ip-172-31-29-142:~# cat    /root/newrelic-npi/plugins/com.tylerhoersch.nr.cassandra/newrelic_cassandra_plugin-1.2.0/logs/newrelic_plugin.log
[2017-05-22 12:51:36,202] DEBUG com.newrelic.metrics.publish.Runner - Setting up agents to be run
[2017-05-22 12:51:36,207] DEBUG com.newrelic.metrics.publish.AgentFactory - Created agent: com.tylerhoersch.nr.cassandra.CassandraAgent@5e91993f
[2017-05-22 12:51:36,210] DEBUG com.newrelic.metrics.publish.Agent - Preparing to run
[2017-05-22 12:51:36,210] DEBUG com.newrelic.metrics.publish.Agent - Setting up metrics
[2017-05-22 12:51:36,213] DEBUG com.newrelic.metrics.publish.Runner - Harvest and report data
[2017-05-22 12:51:36,213] DEBUG com.newrelic.metrics.publish.Runner - Beginning poll cycle for agent: 'ML Cassandra Cluster'
[2017-05-22 12:51:36,418] DEBUG com.newrelic.metrics.publish.Agent - Reporting metric: Cassandra/global/Downtime
[2017-05-22 12:51:36,419] DEBUG com.newrelic.metrics.publish.binding.Request - ComponentData(ML Cassandra Cluster:com.tylerhoersch.nr.cassandra) : Metric: Component/Cassandra/global/Downtime[count], count: 1, value: 0.0, minValue: 0.0, maxValue: 0.0, sumOfSquares: 0.0
[2017-05-22 12:51:36,419] DEBUG com.newrelic.metrics.publish.Runner - Ending poll cycle for agent: 'ML Cassandra Cluster'
[2017-05-22 12:51:36,420] DEBUG com.newrelic.metrics.publish.binding.Request - Sending JSON: {"agent":{"host":"host","pid":0,"version":"1.0.0"},"components":[{"duration":60,"name":"ML Cassandra Cluster","guid":"com.tylerhoersch.nr.cassandra","metrics":{"Component\/Cassandra\/global\/Downtime[count]":[0.0,1,0.0,0.0,0.0]}}]}
[2017-05-22 12:51:36,421] DEBUG com.newrelic.metrics.publish.binding.Context - Metric service url: https://platform-api.newrelic.com/platform/v1/metrics
[2017-05-22 12:51:37,164] DEBUG com.newrelic.metrics.publish.binding.Request - Server response: 200, {"status": "ok"}
[2017-05-22 12:52:36,212] DEBUG com.newrelic.metrics.publish.Runner - Harvest and report data
[2017-05-22 12:52:36,213] DEBUG com.newrelic.metrics.publish.Runner - Beginning poll cycle for agent: 'ML Cassandra Cluster'
[2017-05-22 12:52:36,240] ERROR com.tylerhoersch.nr.cassandra.JMXRunner - 
java.lang.Exception: All hosts (172.31.12.88) tried and failed to connect.
	at com.tylerhoersch.nr.cassandra.JMXRunner.run(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	at com.tylerhoersch.nr.cassandra.CassandraAgent.getCassandraMetrics(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	at com.tylerhoersch.nr.cassandra.CassandraAgent.pollCycle(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:209) [plugin.jar:1.2.0 April 27 2016]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.util.concurrent.ExecutionException: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206) [na:1.8.0_121]
	at com.tylerhoersch.nr.cassandra.JMXRunner.connectWithTimeout(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	... 11 common frames omitted
Caused by: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202) ~[na:1.8.0_121]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:130) ~[na:1.8.0_121]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(Unknown Source) ~[na:1.8.0_121]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430) ~[na:1.8.0_121]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308) ~[na:1.8.0_121]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[na:1.8.0_121]
	at com.tylerhoersch.nr.cassandra.JMXRunner.lambda$connectWithTimeout$2(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	... 3 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_121]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_121]
	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_121]
	at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_121]
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40) ~[na:1.8.0_121]
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613) ~[na:1.8.0_121]
	... 12 common frames omitted
[2017-05-22 12:52:36,241] ERROR com.tylerhoersch.nr.cassandra.CassandraAgent - Error Polling Cassandra: java.lang.Exception: All hosts (172.31.12.88) tried and failed to connect.
[2017-05-22 12:52:36,241] DEBUG com.newrelic.metrics.publish.Runner - Ending poll cycle for agent: 'ML Cassandra Cluster'
[2017-05-22 12:52:36,241] DEBUG com.newrelic.metrics.publish.binding.Request - No metrics were reported for this poll cycle
[2017-05-22 12:53:36,212] DEBUG com.newrelic.metrics.publish.Runner - Harvest and report data
[2017-05-22 12:53:36,213] DEBUG com.newrelic.metrics.publish.Runner - Beginning poll cycle for agent: 'ML Cassandra Cluster'
[2017-05-22 12:53:36,228] ERROR com.tylerhoersch.nr.cassandra.JMXRunner - 
java.lang.Exception: All hosts (172.31.12.88) tried and failed to connect.
	at com.tylerhoersch.nr.cassandra.JMXRunner.run(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	at com.tylerhoersch.nr.cassandra.CassandraAgent.getCassandraMetrics(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	at com.tylerhoersch.nr.cassandra.CassandraAgent.pollCycle(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:209) [plugin.jar:1.2.0 April 27 2016]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.util.concurrent.ExecutionException: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206) [na:1.8.0_121]
	at com.tylerhoersch.nr.cassandra.JMXRunner.connectWithTimeout(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	... 11 common frames omitted
Caused by: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202) ~[na:1.8.0_121]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:130) ~[na:1.8.0_121]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(Unknown Source) ~[na:1.8.0_121]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430) ~[na:1.8.0_121]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308) ~[na:1.8.0_121]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[na:1.8.0_121]
	at com.tylerhoersch.nr.cassandra.JMXRunner.lambda$connectWithTimeout$2(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	... 3 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_121]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_121]
	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_121]
	at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_121]
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40) ~[na:1.8.0_121]
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613) ~[na:1.8.0_121]
	... 12 common frames omitted
[2017-05-22 12:53:36,228] ERROR com.tylerhoersch.nr.cassandra.CassandraAgent - Error Polling Cassandra: java.lang.Exception: All hosts (172.31.12.88) tried and failed to connect.
[2017-05-22 12:53:36,229] DEBUG com.newrelic.metrics.publish.Runner - Ending poll cycle for agent: 'ML Cassandra Cluster'
[2017-05-22 12:53:36,229] DEBUG com.newrelic.metrics.publish.binding.Request - No metrics were reported for this poll cycle
[2017-05-22 12:54:36,212] DEBUG com.newrelic.metrics.publish.Runner - Harvest and report data
[2017-05-22 12:54:36,213] DEBUG com.newrelic.metrics.publish.Runner - Beginning poll cycle for agent: 'ML Cassandra Cluster'
[2017-05-22 12:54:36,231] ERROR com.tylerhoersch.nr.cassandra.JMXRunner - 
java.lang.Exception: All hosts (172.31.12.88) tried and failed to connect.
	at com.tylerhoersch.nr.cassandra.JMXRunner.run(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	at com.tylerhoersch.nr.cassandra.CassandraAgent.getCassandraMetrics(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	at com.tylerhoersch.nr.cassandra.CassandraAgent.pollCycle(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:209) [plugin.jar:1.2.0 April 27 2016]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.util.concurrent.ExecutionException: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206) [na:1.8.0_121]
	at com.tylerhoersch.nr.cassandra.JMXRunner.connectWithTimeout(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	... 11 common frames omitted
Caused by: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202) ~[na:1.8.0_121]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:130) ~[na:1.8.0_121]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(Unknown Source) ~[na:1.8.0_121]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430) ~[na:1.8.0_121]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308) ~[na:1.8.0_121]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[na:1.8.0_121]
	at com.tylerhoersch.nr.cassandra.JMXRunner.lambda$connectWithTimeout$2(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	... 3 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_121]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_121]
	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_121]
	at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_121]
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40) ~[na:1.8.0_121]
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613) ~[na:1.8.0_121]
	... 12 common frames omitted
[2017-05-22 12:54:36,232] ERROR com.tylerhoersch.nr.cassandra.CassandraAgent - Error Polling Cassandra: java.lang.Exception: All hosts (172.31.12.88) tried and failed to connect.
[2017-05-22 12:54:36,232] DEBUG com.newrelic.metrics.publish.Runner - Ending poll cycle for agent: 'ML Cassandra Cluster'
[2017-05-22 12:54:36,232] DEBUG com.newrelic.metrics.publish.binding.Request - No metrics were reported for this poll cycle
root@ip-172-31-29-142:~#

**Comment by tfendt** [comment]
What ip do you have set in the config? We run this plugin locally on our dev machines just fine using ip 127.0.0.1.

**Comment by njain1985** [comment]
Hi tfendt,

I had set the cassandra cluster host's public ip in the config. Can you share a sample of a working config file - newrelic.config and plugin.json file with me. Thanks.

**Comment by tfendt** [comment]
The IP(s) specified in the config are the seeds, it will then try to open a jmx connection to all other servers in the cluster. If you have one monitor server gathering metrics from the nodes in your cluster you will need to enable remote JMX.

I'm not sure what you mean by the plugin is local to the cluster. Unless the plugin is installed directly on the Cassandra node you are monitoring then it is not local.

It sounds like you have a cluster made up of more than 1 node and then you created another server to install the this plugin on which is supposed to pull from all the nodes in your cluster?

**Comment by Dmitry1987** [comment]
Same here, tried to make the plugin work against localhost to get info from cassandra, but got 'ERROR com.tylerhoersch.nr.cassandra.CassandraAgent - Error Polling Cassandra: java.lang.Exception: All hosts'

despite I set "localhost" in plugin.json, it tries the "host ip" which is external IP of this node, instead accessing through localhost (and port 7199 only open on localhost)

any advice?

**Comment by Dmitry1987** [comment]
it's ok figured out... @njain1985  
by default port 7199 will be open only on localhost but I was able to make it listen on all interfaces so the plugin now able to connect.  
Had to change this file:    /etc/cassandra/cassandra-env.sh   
set the
**LOCAL_JMX=no**
and 
com.sun.management.jmxremote.authenticate=false
(only if not reachable from internet! be careful. I have it in internal backend network only so it's secure)

```

LOCAL_JMX=no

# Specifies the default port over which Cassandra will be available for
# JMX connections.
# For security reasons, you should not expose this port to the internet.  Firewall it if needed.
JMX_PORT="7199"

if [ "$LOCAL_JMX" = "yes" ]; then
  JVM_OPTS="$JVM_OPTS -Dcassandra.jmx.local.port=$JMX_PORT"
  JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
else
  JVM_OPTS="$JVM_OPTS -Dcassandra.jmx.remote.port=$JMX_PORT"
  JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.rmi.port=$JMX_PORT"
  JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
fi

```
