### ISSUE TITLE
Plugin is started but getting the following error

### ISSUE THREAD

**Issue by kavin2703** [thoersch/new-relic-cassandra#16]
ERROR com.tylerhoersch.nr.cassandra.JMXRunner -
java.lang.Exception: All hosts (xx.xx.xx.xx) tried and failed to connect.
        at com.tylerhoersch.nr.cassandra.JMXRunner.run(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
        at com.tylerhoersch.nr.cassandra.CassandraAgent.getCassandraInstances(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
        at com.tylerhoersch.nr.cassandra.CassandraAgent.pollCycle(Unknown Source) [plugin.jar:1.2.0 April 27 2016]
        at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:209) [plugin.jar:1.2.0 April 27 2016]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_162]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 172.31.103.149; nested exception is:
        java.net.ConnectException: Connection refused (Connection refused)]
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_162]
        at java.util.concurrent.FutureTask.get(FutureTask.java:206) [na:1.8.0_162]
        at com.tylerhoersch.nr.cassandra.JMXRunner.connectWithTimeout(Unknown Source) [plugin.jar:1.2.0 April 27 2016]

**Comment by thoersch** [comment]
Error seems pretty straight forward. The sever you have the monitor running on cannot speak with the server you've given it to communicate with:

`Connection refused to host: 172.31.103.149`

Verify these 2 can talk and that cassandra is running and accessible

**Comment by kavin2703** [comment]
Thanks It works well configured it again 👍
