### ISSUE TITLE
Can't run plugin

### ISSUE THREAD

**Issue by srdayman** [thoersch/new-relic-cassandra#3]
When attempting to run plugin, I get the following error. I've tried this on several machines. 

java -jar ./plugin.jar  
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/tylerhoersch/nr/cassandra/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by thoersch** [comment]
Hi @srdayman,

I did some googling around that error since I had not seen it before and it looks to come from when the jdk version and the app version are mismatched:

http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

What java and/or javac version is on the machine you're running this from?

**Comment by srdayman** [comment]
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
I guess I should pay closer attention to the requirements in README. Spin up a new VM to run this from with Oracle JRE 1.8

**Comment by thoersch** [comment]
Did running this under a JRE 1.8 work?

**Comment by srdayman** [comment]
It did. Thanks! Any ideas how I can get the plugin to report that a node is down without failing to start? At the moment it is finding a node that's been removed from the ring, logging the error and also not sending any metrics to NR. I'm working on getting the nodes to forget about the removed node but this is proving difficult.

**Comment by thoersch** [comment]
@srdayman in the config, pass it a different host. it will still find it via discovery if the node is in the cluster, but it should start, however it should then report it as down.
